project_id = "awtxvhstozhprjujlsne"

[functions.send-application-email]
verify_jwt = false

[functions.send-getkiku-invitation]
verify_jwt = false

[functions.generate-sitemap]
verify_jwt = false

[functions.ai-recruiter-assistant]
verify_jwt = true

[functions.send-interview-invitation]
verify_jwt = true

[functions.send-interview-reminder]
verify_jwt = false

[functions.send-interview-cancellation]
verify_jwt = true

[functions.invite-user]
verify_jwt = true

[functions.get-users]
verify_jwt = true

[functions.send-job-tip]
verify_jwt = false

[functions.send-nocv-tip]
verify_jwt = false

[functions.generate-screening-assessment]
verify_jwt = true

[functions.generate-final-assessment]
verify_jwt = true

[functions.generate-job-ad]
verify_jwt = true
